language: csharp
mono: none
dotnet: 2.1.200
git:
 depth: 3
branches:
 only:
 - nightly
before_install: true
install: true
before_script: true
script:
 - cd MDACSApp
 - npm install babel-cli
 - npm install babel-plugin-transform-react-jsx
 - dotnet run
 - git config --local user.name "Travis-CI"
 - git config --local user.email "none@none.none"
 - printf -- "$GHSSHK" > ~/.ssh/id_github_mdacs
 - chmod 600 ~/.ssh/id_github_mdacs
 - echo "Host github.com" >> ~/.ssh/config
 - echo "  IdentityFile ~/.ssh/id_github_mdacs" >> ~/.ssh/config
 - chmod 600 ~/.ssh/config
 - mkdir ~/tmp/
 - mkdir ~/tmp/webres
 - cp ./bin/Debug/netcoreapp2.0/* ~/tmp/
 - cp ./webres/* ~/tmp/webres/
 - cd ~
 - git clone git@github.com:kmcguire3413/MDACSDeliverables.git
 - cd MDACSDeliverables
 - cd Nightly
 - mkdir -p MDACSApp
 - cd MDACSApp
 - mkdir -p webres
 - cp ~/tmp/* ./
 - cp ~/tmp/webres/* ./webres/
 - git add *
 - git add ./webres/*
 - git commit -m "travis-ci automated deploy of nightly MDACSApp"
 - git push origin master 
before_cache: true
before_deploy: true
deploy:
        skip_cleanup: false
after_deploy: true
after_script: true

